controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - shoulder_joint
      - forearm_shoulder_joint
      - elbow_joint
      - roll_joint
      - yaw_joint
      - roll_2_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - left_finger_joint
      - right_finger_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: close