# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_joint
    - forearm_shoulder_joint
    - elbow_joint
    - roll_joint
    - yaw_joint
    - roll_2_joint
    - left_finger_joint
    - right_finger_joint
    - left_wheel_joint
    - right_wheel_joint
    - dorso_arm_base
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: arm_follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_joint
      - forearm_shoulder_joint
      - elbow_joint
      - roll_joint
      - yaw_joint
      - roll_2_joint
  - name: rail_controller
    action_ns: rail_follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - dorso_arm_base
  - name: gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    parallel: true
    joints:
      - left_finger_joint
      - right_finger_joint
arm_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  action_ns: arm_follow_joint_trajectory
  joints:
    - shoulder_joint
    - forearm_shoulder_joint
    - elbow_joint
    - roll_joint
    - yaw_joint
    - roll_2_joint
  gains:
    shoulder_joint:
      p: 100.0
      d: 0.0
      i: 0.0
    forearm_shoulder_joint:
      p: 100.0
      d: 0.0
      i: 0.0
    elbow_joint:
      p: 100.0
      d: 0.0
      i: 0.0
    roll_joint:
      p: 100.0
      d: 0.0
      i: 0.0
    yaw_joint:
      p: 100.0
      d: 0.0
      i: 0.0
    roll_2_joint:
      p: 100.0
      d: 0.0
      i: 0.0
gripper_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  action_ns: gripper_action
  joints:
    - left_finger_joint
    - right_finger_joint
  gains:
    left_finger_joint:
      p: 100.0
      d: 0.0
      i: 0.0
    right_finger_joint:
      p: 100.0
      d: 0.0
      i: 0.0
rail_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  action_ns: rail_follow_joint_trajectory
  joints:
    - dorso_arm_base
  gains:
    dorso_arm_base:
      p: 100.0
      d: 0.0
      i: 0.0
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: home
