controller_list:
  - name: fake_arm_controller
    joints:
      - soulder_base_joint
      - shoulder_forearm_joint
      - arm_forearm_joint
      - roll_arm_joint
      - yaw_roll_joint
      - pitch_yaw_joint
  - name: fake_gripper_controller
    joints:
      - gripper_left_pitch
      - gripper_right_pitch
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: close